language: node_js

node_js:
- '10'

install: npm install

script:
  - npm run lint
  - npm run build
  - npm test

deploy:
  skip_cleanup: true
  
  - provider: firebase
    token: $FIREBASE_TOKEN
    on:
      branch: master
    project: honesty-store-kiosk-dev

  - provider: firebase
    token: $FIREBASE_TOKEN
    on:
      branch: env-QA
    project: honesty-store-kiosk-qa

  - provider: firebase
    token: $FIREBASE_TOKEN
    on:
      branch: env-Prod
    project: honesty-store-kiosk