language: node_js

node_js:
  - '10'

branches:
  only:
    - master
    - config

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master

script:
  - npm install && npm test
  - npm install -g firebase-tools
  