language: node_js

node_js:
  - '10'

branches:
  only:
    - master
    - config

script:
  - npm install && npm test
  - npm install -g firebase-tools
  - rm -r node_modules/@tensorflow/tfjs-converter/dist-es6
  - npm run deploy